# Previously we talked about error handlign by the use of try and except block
# So today we will be talking about finally keyword in python
# We can use finally with try and except keyword
# PS : 